name: 'Add PR review checklist'
author: Michael Schlottke-Lakemper
description: 'Automatically add a review checklist to newly created pull requests'
inputs:
  file:
    description: 'Path to review checklist file in current repository.'
    required: true
    default: '.github/review-checklist.md'
runs:
  using: "composite"
  steps:
    - name: Read review checklist template from file
      run: |
        {
          echo 'REVIEW_CHECKLIST<<REVIEW_CHECKLIST_EOF'
          cat '${{ inputs.file }}'
          echo
          echo 'REVIEW_CHECKLIST_EOF'
        } >> "$GITHUB_ENV"
    - name: Add review checklist as comment
      uses: actions/github-script@v6
      with:
        script: |
          const { REVIEW_CHECKLIST } = process.env;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: REVIEW_CHECKLIST,
          });
